name: Java CI

on:
  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps: 

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Build and test
        run: ./mvnw --batch-mode verify
