name: Java CI

on:
  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps: 

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Build and test
        run: ./mvnw --batch-mode verify

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: task-manager-jar
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: task-manager-jar

      - name: Start application
        run: |
          java -jar task-manager-0.0.1-SNAPSHOT.jar > application.log 2>&1 &
          echo $! > app.pid
          sleep 10
          cat application.log

      - name: smoke test
        run: |
          curl --fail http://localhost:8080
